package comth.text.baoqi.myapplication.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myDBDaoConfig;

    private final DataCategoryDao myDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myDBDaoConfig = daoConfigMap.get(DataCategoryDao.class).clone();
        myDBDaoConfig.initIdentityScope(type);


        myDBDao = new DataCategoryDao(myDBDaoConfig, this);

        registerDao(MyDBData.class, myDBDao);
    }

    public void clear() {
        myDBDaoConfig.getIdentityScope().clear();
    }

    public DataCategoryDao getDataDao() {
        return myDBDao;
    }

}
